#pragma config(Sensor, S1,     rightSonicSensor, sensorSONAR)
#pragma config(Sensor, S2,     rightLightSensor, sensorLightActive)
#pragma config(Sensor, S3,     leftLightSensor, sensorLightActive)
#pragma config(Sensor, S4,     leftSonicSensor, sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

// line following
while(true)
	{
		if(SensorValue(rightLightSensor) < 41)
		{
			motor[motorC] = -100;
			motor[motorB] = 0;
		}

		if(SensorValue(rightLightSensor) > 41)
		{
			motor[motorC] = 0;
			motor[motorB] = -100;
		}

		if(SensorValue(leftLightSensor) < 41)
		{
			motor[motorC] = 0;
			motor[motorB] = -100;
		}

		if(SensorValue(leftLightSensor) > 41)
		{
			motor[motorC] = -100;
			motor[motorB] = 0;
		}
	}

}
